config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'users/show'

  resources :codes
  root 'static#home'

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  #devise_for :users, controllers: { :registrations => "users/registrations" }
  #devise_for :users, :controllers => { registrations: 'registrations' }
  #get '/signup',   to: 'registrations#create'
  # resources :secretcode
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
      can :manage, :all
    else
      can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/code.rb
class Code < ApplicationRecord
    belongs_to :user, :optional => true
end

app/models/secretcode.rb
class Secretcode < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :code

  #validates :secret_code, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  helper_method :generate_uuid
  before_action :set_code, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def generate_uuid
    p SecureRandom.hex(5)
  end

  def index
    @codes = Code.all
  end

  def show

  end

  def new
    @code = Code.new
  end

  def edit

  end
 
  def create
    @code = Code.new(code_params)

    respond_to do |format|
      if @code.save
        format.html { redirect_to @code, notice: 'Code was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  private
    def set_code
      @code = Code.find(params[:id])
    end

    def code_params
      params.require(:code).permit(:secretcode, :uuid)
    end
end

app/controllers/registration_controller.rb
class RegistraionsController < Devise::RegistrationsController

    private
    def sign_up_params
      params.require(:user).permit(:first, :last, :email, :secret_code, :password, :password_confirmation)
    end
  
    def account_update_params
      params.require(:user).permit(:first, :last, :secret_code :email, :password, :password_confirmation, :current_password)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
      params.require(:user).permit(:first, :last, :email, :secret_code, :password, :password_confirmation)
    end
  
    def account_update_params
      params.require(:user).permit(:first, :last, :email, :secret_code, :password, :password_confirmation, :current_password)
    end

end

app/controllers/secretcode_controller.rb
class SecretcodeController < ApplicationController
    
  def index
     @secretcodes = Secretcode.all
  end

  def new
   @secretcode = Secretcode.new
  end

  def create
     @secretcode = Secretcode.new(secretcode_params)
     if @secretcode.save
        flash[:success] = "Secret Code Created Succesfully"
        redirect_to @secretcode
     else
        render 'index'
     end
  end

  def secretcode_params
     params.require(:secretcode).permit(:code)
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = user.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
   if @user.update_attributes(secure_params)
    redirect_to root_path, notice => 'Success'
   else
    redirect_to root_path, :alert => 'Wrong'
   end
  end

  private
   def secure_params
    params.require(:user).permit(:role)
   end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/helpers/secretcode_helper.rb
module SecretcodeHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/codes/_form.html.erb
<%= form_with(model: code, local: true) do |form| %>
  <% if code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(code.errors.count, "error") %> prohibited this code from being saved:</h2>

      <ul>
      <% code.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   <%= form.label :secretcode %>
   <%= form.text_field :secretcode %>
  </div>
<br>
  <div class="field">
   <%= form.label :Number %>
   <%= form.select :desired_attribute, ['10', '20', '30', '50'] %>
  </div>
  <br>

  <div class="field">
   <%= form.label :code %>
   <%= form.text_field :uuid, :value => generate_uuid %>
  </div>
  
  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/codes/edit.html.erb
<h1>Editing Code</h1>

<%= render 'form', code: @code %>

<%= link_to 'Show', @code %> |
<%= link_to 'Back', codes_path %>

app/views/codes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Codes</h1>

<table>

  <thead>
    <tr>
      <th>Secretcode</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @codes.each do |code| %>

      <tr>

        <td><%= code.uuid %></td>
        
        <% # code.user.email %>

        <% if code.user %>

        <td><%= code.user.email %></td>

        <% else %>
        
        <td>Email is not associated</td>
        
        <% end %>

      </tr>
    <% end %>
  </tbody>

</table>
<br>

<%= link_to 'Generate Code', new_code_path %>

app/views/codes/new.html.erb
<h1>Generate New Code</h1>

<%= render 'form', code: @code %>

<%= link_to 'Back', codes_path %>

app/views/codes/show.html.erb
<p>
  <strong>Secretcode:</strong>
  <%= @code.uuid %>
</p>

<%= link_to 'Edit', edit_code_path(@code) %> |
<%= link_to 'Back', codes_path %>

app/views/layouts/_footer.html.erb
<br>
<br>
<br>
<footer class="footer">
  <small>
    The <a href="#">ROR</a>
    by <a href="#">Pradeep Rao</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Admin", root_path, id: "logo" %>
    <nav>

     <ul class="nav navbar-nav navbar-right">
     <% if current_user && current_user.admin %>
        <li><%= link_to "Codes", codes_path %></li>
        <% end %>
      </ul>

    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  <head>
    <title>EngineerAssingment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <%= render 'layouts/header' %>

  <body>
  <div class="container">
   <p class="notice"><%= notice %></p>

   <p class="alert"><%= alert %></p>

   <%= yield %>

  </div>

   <%= render 'layouts/footer' %>

  </body>
</html>

app/views/secretcode/_form.html.erb
<%= form_with(model: secretcodes, local: true) do |form| %>
  
  <% if secretcode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(secretcode.errors.count, "error") %> prohibited this secretcode from being saved:</h2>

      <ul>
      <% secretcode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/secretcode/index.html.erb
<h1>Secretcode Generator</h1>

<p id="notice"><%= notice %></p>

<table>

  <thead>
    <tr>
      <th>Code</th>
      <th colspan="3"></th>
      <th>Email Associated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @secretcodes.each do |secretcode| %>
      <tr>
        <td><%= secretcode.code %></td>
        <td><%= secretcode.user.email %></td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/secretcode/new.html.erb
<%= form_for(@secretcode) do |f| %>
    <%= f.label :code %>
    <%= f.text_field :code %>
    <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>